- name: Configure and Start
  hosts: prod
  become: yes
  tasks:
    - name: Setup virtual environment
      command: "python3 -m venv /home/ubuntu/myFlaskApp/env"

    - name: Activate virtual environment
      command: "bash -c 'source /home/ubuntu/myFlaskApp/env/bin/activate'"

    - name: Install Flask and Gunicorn
      pip:
        requirements: /home/ubuntu/myFlaskApp/requirements_prod.txt

    - name: Create WSGI entry point
      copy:
        content: |
          from app import app
          if __name__ == "__main__":
              app.run()
        dest: "/home/ubuntu/myFlaskApp/wsgi.py"

    - name: Create Gunicorn systemd service
      template:
        src: "/var/lib/jenkins/workspace/Flask_App/deploy-config/deployment/roles/flask_app/templates/app.service.j2"
        dest: /etc/systemd/system/app.service
      notify: Restart Gunicorn

    - name: Configure Nginx
      template:
        src: "/var/lib/jenkins/workspace/Flask_App/deploy-config/deployment/roles/flask_app/templates/app.nginx.j2"
        dest: /etc/nginx/sites-available/app
      notify: Restart Nginx

  handlers:
    - name: Restart Gunicorn
      systemd:
        name: app
        state: restarted
        
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted
